export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_CLEAR_ITEMS = 'CART_RESET'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'


export const CART_CHECK_OUT_REQUEST = 'CART_CHECK_OUT_REQUEST'
export const CART_CHECK_OUT_SUCCESS = 'CART_CHECK_OUT_SUCCESS'
export const CART_CHECK_OUT_FAIL = 'CART_CHECK_OUT_FAIL'


export const GET_RATES_REQUEST = 'GET_RATES_REQUEST'
export const GET_RATES_SUCCESS = 'GET_RATES_SUCCESS'
export const GET_RATES_FAIL = 'GET_RATES_FAIL'

