export const PAYMENT_CHECK_CARD_REQUEST = 'CART_CHECK_CARD_REQUEST'
export const PAYMENT_CHECK_CARD_SUCCESS = 'PAYMENT_CHECK_CARD_SUCCESS'
export const PAYMENT_CHECK_CARD_FAIL = 'PAYMENT_CHECK_CARD_FAIL'
export const PAYMENT_CHECK_CARD_RESET = 'PAYMENT_CHECK_CARD_RESET'

export const PAYMENT_CHECK_PIN_REQUEST = 'CART_CHECK_PIN_REQUEST'
export const PAYMENT_CHECK_PIN_SUCCESS = 'PAYMENT_CHECK_PIN_SUCCESS'
export const PAYMENT_CHECK_PIN_FAIL = 'PAYMENT_CHECK_PIN_FAIL'
export const PAYMENT_CHECK_PIN_RESET = 'PAYMENT_CHECK_PIN_RESET'

export const PAYMENT_CHECK_CCV_REQUEST = 'CART_CHECK_CCV_REQUEST'
export const PAYMENT_CHECK_CCV_SUCCESS = 'PAYMENT_CHECK_CCV_SUCCESS'
export const PAYMENT_CHECK_CCV_FAIL = 'PAYMENT_CHECK_CCV_FAIL'
export const PAYMENT_CHECK_CCV_RESET = 'PAYMENT_CHECK_CCV_RESET'

export const PAYMENT_PAY_REQUEST = 'CART_PAY_REQUEST'
export const PAYMENT_PAY_SUCCESS = 'PAYMENT_PAY_SUCCESS'
export const PAYMENT_PAY_FAIL = 'PAYMENT_CHECK_CCV_FAIL'
export const PAYMENT_PAY_RESET = 'PAYMENT_PAY_RESET'